/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapplication;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author markk
 */
public class PollGui extends javax.swing.JFrame {

    ArrayList<Question> poll;

    /**
     * Creates new form PollGui
     */
    public PollGui() {
        initComponents();

        poll = new ArrayList<>();

        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3Group = new javax.swing.ButtonGroup();
        ageGroup = new javax.swing.ButtonGroup();
        panel6Group = new javax.swing.ButtonGroup();
        panel5Group = new javax.swing.ButtonGroup();
        panel4Group = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panelTwo = new javax.swing.JPanel();
        mainHeadingLbl1 = new javax.swing.JLabel();
        loadBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelThree = new javax.swing.JPanel();
        p3mainHeadingLbl = new javax.swing.JLabel();
        p3candidateComboBox = new javax.swing.JComboBox<>();
        p3maleBtn = new javax.swing.JRadioButton();
        p3femaleBtn = new javax.swing.JRadioButton();
        p3Q1Lbl = new javax.swing.JLabel();
        p3Q2Lbl = new javax.swing.JLabel();
        p3Answer1TF = new javax.swing.JTextField();
        p3Answer2TF = new javax.swing.JTextField();
        p3SubmitBtn = new javax.swing.JButton();
        panelFour = new javax.swing.JPanel();
        p4mainHeadingLbl = new javax.swing.JLabel();
        p4candidateComboBox = new javax.swing.JComboBox<>();
        p4maleBtn = new javax.swing.JRadioButton();
        p4femaleBtn = new javax.swing.JRadioButton();
        p4Q1Lbl = new javax.swing.JLabel();
        p4Q2Lbl = new javax.swing.JLabel();
        p4Answer1TF = new javax.swing.JTextField();
        p4Answer2TF = new javax.swing.JTextField();
        p4SubmitBtn = new javax.swing.JButton();
        panelFive = new javax.swing.JPanel();
        p5mainHeadingLbl = new javax.swing.JLabel();
        p5candidateComboBox = new javax.swing.JComboBox<>();
        p5maleBtn = new javax.swing.JRadioButton();
        p5femaleBtn = new javax.swing.JRadioButton();
        p5Q1Lbl = new javax.swing.JLabel();
        p5Q2Lbl = new javax.swing.JLabel();
        p5Answer1TF = new javax.swing.JTextField();
        p5Answer2TF = new javax.swing.JTextField();
        p5SubmitBtn = new javax.swing.JButton();
        panelSix = new javax.swing.JPanel();
        p6mainHeadingLbl = new javax.swing.JLabel();
        p6candidateComboBox = new javax.swing.JComboBox<>();
        p6maleBtn = new javax.swing.JRadioButton();
        p6femaleBtn = new javax.swing.JRadioButton();
        p6Q1Lbl = new javax.swing.JLabel();
        p6Q2Lbl = new javax.swing.JLabel();
        p6Answer1TF = new javax.swing.JTextField();
        p6Answer2TF = new javax.swing.JTextField();
        p6SubmitBtn = new javax.swing.JButton();
        panelSeven = new javax.swing.JPanel();
        p7mainHeadingLbl = new javax.swing.JLabel();
        ageGrp1Btn = new javax.swing.JRadioButton();
        ageGrp2Btn = new javax.swing.JRadioButton();
        ageGrp3Btn = new javax.swing.JRadioButton();
        ageGrp4Btn = new javax.swing.JRadioButton();
        ageGroupLbl = new javax.swing.JLabel();
        panelOne = new javax.swing.JPanel();
        mainHeadingLbl = new javax.swing.JLabel();
        userTypeLbl = new javax.swing.JLabel();
        adminUserBtn = new javax.swing.JButton();
        voterUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(806, 300));
        mainPanel.setLayout(new java.awt.CardLayout());

        mainHeadingLbl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        mainHeadingLbl1.setText("Election Application 2018");

        loadBTN.setBackground(new java.awt.Color(0, 215, 255));
        loadBTN.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        loadBTN.setText("Load");
        loadBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loadBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        saveBTN.setBackground(new java.awt.Color(0, 215, 255));
        saveBTN.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 215, 255));
        jButton3.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jButton3.setText("View");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 215, 255));
        jButton4.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTwoLayout = new javax.swing.GroupLayout(panelTwo);
        panelTwo.setLayout(panelTwoLayout);
        panelTwoLayout.setHorizontalGroup(
            panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoLayout.createSequentialGroup()
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTwoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainHeadingLbl1))
                    .addGroup(panelTwoLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(230, 230, 230)
                        .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        panelTwoLayout.setVerticalGroup(
            panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainHeadingLbl1)
                .addGap(152, 152, 152)
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(panelTwo, "card3");

        panelThree.setPreferredSize(new java.awt.Dimension(1006, 579));

        p3mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        p3mainHeadingLbl.setText("Election Applicaion 2018");

        p3candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada4" }));

        p3maleBtn.setBackground(getBackground());
        panel3Group.add(p3maleBtn);
        p3maleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p3maleBtn.setText("Male");
        p3maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p3maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p3femaleBtn.setBackground(getBackground());
        panel3Group.add(p3femaleBtn);
        p3femaleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p3femaleBtn.setText("Female");
        p3femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p3femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p3Q1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Q1Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p3Q1Lbl.setText("Q1: Is this your first time voting?");

        p3Q2Lbl.setBackground(new java.awt.Color(51, 51, 255));
        p3Q2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Q2Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p3Q2Lbl.setText("Q2: Have you lived abroad (> 3 month period)?");

        p3Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p3Answer1TF.setPreferredSize(new java.awt.Dimension(653, 28));
        p3Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3Answer1TFActionPerformed(evt);
            }
        });

        p3Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Answer2TF.setForeground(new java.awt.Color(255, 0, 0));
        p3Answer2TF.setPreferredSize(new java.awt.Dimension(653, 28));
        p3Answer2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3Answer2TFActionPerformed(evt);
            }
        });

        p3SubmitBtn.setBackground(new java.awt.Color(0, 215, 255));
        p3SubmitBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p3SubmitBtn.setText("Submit");
        p3SubmitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p3SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p3SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3SubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThreeLayout = new javax.swing.GroupLayout(panelThree);
        panelThree.setLayout(panelThreeLayout);
        panelThreeLayout.setHorizontalGroup(
            panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeLayout.createSequentialGroup()
                .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThreeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p3SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p3Q2Lbl)
                                .addComponent(p3Q1Lbl)
                                .addComponent(p3mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p3Answer1TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p3Answer2TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelThreeLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(p3maleBtn)
                        .addGap(167, 167, 167)
                        .addComponent(p3femaleBtn))
                    .addGroup(panelThreeLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        panelThreeLayout.setVerticalGroup(
            panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p3mainHeadingLbl)
                .addGap(38, 38, 38)
                .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3maleBtn)
                    .addComponent(p3femaleBtn))
                .addGap(47, 47, 47)
                .addComponent(p3Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p3Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p3Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p3Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(p3SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        mainPanel.add(panelThree, "card4");

        p4mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        p4mainHeadingLbl.setText("Election Applicaion 2018");

        p4candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel4Group.add(p4maleBtn);
        p4maleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p4maleBtn.setText("Male");
        p4maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panel4Group.add(p4femaleBtn);
        p4femaleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p4femaleBtn.setText("Female");
        p4femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p4Q1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Q1Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p4Q1Lbl.setText("Q1: Have you voted in previous presidential elections?");

        p4Q2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Q2Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p4Q2Lbl.setText("Q2: What is your marrage status?");

        p4Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p4Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4Answer1TFActionPerformed(evt);
            }
        });

        p4Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p4SubmitBtn.setBackground(new java.awt.Color(0, 215, 255));
        p4SubmitBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p4SubmitBtn.setText("Submit");
        p4SubmitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p4SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4SubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFourLayout = new javax.swing.GroupLayout(panelFour);
        panelFour.setLayout(panelFourLayout);
        panelFourLayout.setHorizontalGroup(
            panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourLayout.createSequentialGroup()
                .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFourLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p4SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p4Q2Lbl)
                                .addComponent(p4Q1Lbl)
                                .addComponent(p4mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p4Answer2TF)
                                .addComponent(p4Answer1TF))))
                    .addGroup(panelFourLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFourLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(p4maleBtn)
                        .addGap(143, 143, 143)
                        .addComponent(p4femaleBtn)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        panelFourLayout.setVerticalGroup(
            panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p4mainHeadingLbl)
                .addGap(40, 40, 40)
                .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4femaleBtn)
                    .addComponent(p4maleBtn))
                .addGap(48, 48, 48)
                .addComponent(p4Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p4Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p4Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p4Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(p4SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        mainPanel.add(panelFour, "card5");

        p5mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        p5mainHeadingLbl.setText("Election Applicaion 2018");

        p5candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel5Group.add(p5maleBtn);
        p5maleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p5maleBtn.setText("Male");
        p5maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panel5Group.add(p5femaleBtn);
        p5femaleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p5femaleBtn.setText("Female");
        p5femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p5Q1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Q1Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p5Q1Lbl.setText("Q1: Do you have any children?");

        p5Q2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Q2Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p5Q2Lbl.setText("Q2: If you own a car, what type of of car is it (diesel / petrol / hybrid / electric)?");

        p5Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p5Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5Answer1TFActionPerformed(evt);
            }
        });

        p5Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p5SubmitBtn.setBackground(new java.awt.Color(0, 215, 255));
        p5SubmitBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p5SubmitBtn.setText("Submit");
        p5SubmitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p5SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5SubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiveLayout = new javax.swing.GroupLayout(panelFive);
        panelFive.setLayout(panelFiveLayout);
        panelFiveLayout.setHorizontalGroup(
            panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveLayout.createSequentialGroup()
                .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiveLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p5SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p5Q2Lbl)
                                .addComponent(p5Q1Lbl)
                                .addComponent(p5mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p5Answer2TF)
                                .addComponent(p5Answer1TF))))
                    .addGroup(panelFiveLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiveLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(p5maleBtn)
                        .addGap(129, 129, 129)
                        .addComponent(p5femaleBtn)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        panelFiveLayout.setVerticalGroup(
            panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p5mainHeadingLbl)
                .addGap(41, 41, 41)
                .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5femaleBtn)
                    .addComponent(p5maleBtn))
                .addGap(51, 51, 51)
                .addComponent(p5Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p5Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(p5SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        mainPanel.add(panelFive, "card6");

        p6mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        p6mainHeadingLbl.setText("Election Applicaion 2018");

        p6candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel6Group.add(p6maleBtn);
        p6maleBtn.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        p6maleBtn.setText("Male");
        p6maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p6maleBtn.setContentAreaFilled(false);
        p6maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panel6Group.add(p6femaleBtn);
        p6femaleBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p6femaleBtn.setText("Female");
        p6femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p6femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p6Q1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Q1Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p6Q1Lbl.setText("Q1: Who did you vote for in the previous presidential election?");

        p6Q2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Q2Lbl.setForeground(new java.awt.Color(51, 51, 255));
        p6Q2Lbl.setText("Q2: Do you have a smart phone?");

        p6Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p6Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6Answer1TFActionPerformed(evt);
            }
        });

        p6Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p6SubmitBtn.setBackground(new java.awt.Color(0, 215, 255));
        p6SubmitBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        p6SubmitBtn.setText("Submit");
        p6SubmitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p6SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p6SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6SubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSixLayout = new javax.swing.GroupLayout(panelSix);
        panelSix.setLayout(panelSixLayout);
        panelSixLayout.setHorizontalGroup(
            panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p6SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p6Q2Lbl)
                        .addComponent(p6Q1Lbl)
                        .addComponent(p6mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSixLayout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(p6maleBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p6femaleBtn)
                            .addGap(142, 142, 142))
                        .addComponent(p6Answer2TF)
                        .addComponent(p6Answer1TF)
                        .addGroup(panelSixLayout.createSequentialGroup()
                            .addGap(238, 238, 238)
                            .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        panelSixLayout.setVerticalGroup(
            panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p6mainHeadingLbl)
                .addGap(50, 50, 50)
                .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6femaleBtn)
                    .addComponent(p6maleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(p6Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p6Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p6Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p6Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(p6SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        mainPanel.add(panelSix, "card7");

        p7mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        p7mainHeadingLbl.setText("Election Applicaion 2018");

        ageGroup.add(ageGrp1Btn);
        ageGrp1Btn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        ageGrp1Btn.setText("18 - 25");
        ageGrp1Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp1BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp2Btn);
        ageGrp2Btn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        ageGrp2Btn.setText("26 - 40");
        ageGrp2Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp2BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp3Btn);
        ageGrp3Btn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        ageGrp3Btn.setText("41 - 65");
        ageGrp3Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp3BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp4Btn);
        ageGrp4Btn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        ageGrp4Btn.setText("> 65");
        ageGrp4Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp4Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp4BtnActionPerformed(evt);
            }
        });

        ageGroupLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ageGroupLbl.setText("Age Group:");

        javax.swing.GroupLayout panelSevenLayout = new javax.swing.GroupLayout(panelSeven);
        panelSeven.setLayout(panelSevenLayout);
        panelSevenLayout.setHorizontalGroup(
            panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSevenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p7mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(320, 320, 320))
            .addGroup(panelSevenLayout.createSequentialGroup()
                .addGroup(panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSevenLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageGrp1Btn)
                            .addComponent(ageGrp3Btn))
                        .addGap(167, 167, 167)
                        .addGroup(panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageGrp4Btn)
                            .addComponent(ageGrp2Btn)))
                    .addGroup(panelSevenLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(ageGroupLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSevenLayout.setVerticalGroup(
            panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSevenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p7mainHeadingLbl)
                .addGap(79, 79, 79)
                .addComponent(ageGroupLbl)
                .addGap(62, 62, 62)
                .addGroup(panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGrp1Btn)
                    .addComponent(ageGrp2Btn))
                .addGap(71, 71, 71)
                .addGroup(panelSevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGrp3Btn)
                    .addComponent(ageGrp4Btn))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        mainPanel.add(panelSeven, "card8");

        panelOne.setPreferredSize(new java.awt.Dimension(1006, 560));

        mainHeadingLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        mainHeadingLbl.setText("Election Applicaion 2018");

        userTypeLbl.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        userTypeLbl.setText("User type:");

        adminUserBtn.setBackground(new java.awt.Color(0, 215, 255));
        adminUserBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        adminUserBtn.setText("Admin");
        adminUserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminUserBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        adminUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserBtnActionPerformed(evt);
            }
        });

        voterUserBtn.setBackground(new java.awt.Color(0, 215, 255));
        voterUserBtn.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        voterUserBtn.setText("Voter");
        voterUserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voterUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voterUserBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        voterUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOneLayout = new javax.swing.GroupLayout(panelOne);
        panelOne.setLayout(panelOneLayout);
        panelOneLayout.setHorizontalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneLayout.createSequentialGroup()
                .addGroup(panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainHeadingLbl))
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(adminUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(voterUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(userTypeLbl)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        panelOneLayout.setVerticalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainHeadingLbl)
                .addGap(136, 136, 136)
                .addComponent(userTypeLbl)
                .addGap(18, 18, 18)
                .addGroup(panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voterUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(panelOne, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserBtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(true);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_adminUserBtnActionPerformed

    private void voterUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterUserBtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(true);
    }//GEN-LAST:event_voterUserBtnActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try {
            inFile = new File("votes.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream); 
            
            poll = (ArrayList<Question>) oStream.readObject();
            
           oStream.close(); 

        }

         catch (IOException e) {
            System.out.println("There was an error writing to file: " + e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PollGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadBTNActionPerformed

    private void p3Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3Answer1TFActionPerformed

    private void p4Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4Answer1TFActionPerformed

    private void p5Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5Answer1TFActionPerformed

    private void p6Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6Answer1TFActionPerformed

    private void ageGrp1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp1BtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(false);
        panelThree.setVisible(true);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_ageGrp1BtnActionPerformed

    private void ageGrp2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp2BtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(true);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_ageGrp2BtnActionPerformed

    private void ageGrp3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp3BtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(true);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_ageGrp3BtnActionPerformed

    private void ageGrp4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp4BtnActionPerformed
        // TODO add your handling code here:
        panelOne.setVisible(false);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(true);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_ageGrp4BtnActionPerformed

    private void p3SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q;

        String candidate = (String) p3candidateComboBox.getSelectedItem();

        if (voterAge.equals("18 - 25")) {
            q1 = p3Answer1TF.getText();
            q2 = p3Answer2TF.getText();

            //convert gender group btn to String
            if (p3maleBtn.isSelected()) {
                gender = p3maleBtn.getText();
            }
            if (p3femaleBtn.isSelected()) {
                gender = p3maleBtn.getText();
            }
            q = new age18to25(voterAge, candidate, gender, q1, q2);
            poll.add(q);

        }

        //move to panel one - new voter or admin
        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
        //clear inputs
        p3Answer1TF.setText("");
        p3Answer2TF.setText("");
        ageGroup.clearSelection();
        panel3Group.clearSelection();


    }//GEN-LAST:event_p3SubmitBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for (Question x : poll) {

            if (x instanceof age18to25) {
                age18to25 myA1 = (age18to25) x;
                JOptionPane.showMessageDialog(null, myA1.printDetails());

            } else if (x instanceof age25to40) {
                age25to40 myA2 = (age25to40) x;
                JOptionPane.showMessageDialog(null, myA2.printDetails());

            } else if (x instanceof age40to65) {
                age40to65 myA3 = (age40to65) x;
                JOptionPane.showMessageDialog(null, myA3.printDetails());

            } else if (x instanceof ageOver65) {
                ageOver65 myA4 = (ageOver65) x;
                JOptionPane.showMessageDialog(null, myA4.printDetails());
                
            } else {
                JOptionPane.showMessageDialog(null, x.printDetails());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void p4SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q;

        String candidate = (String) p4candidateComboBox.getSelectedItem();

        if (voterAge.equals("26 - 40")) {
            q1 = p4Answer1TF.getText();
            q2 = p4Answer2TF.getText();

            //convert gender group btn to String
            if (p4maleBtn.isSelected()) {
                gender = p4maleBtn.getText();
            }
            if (p4femaleBtn.isSelected()) {
                gender = p4maleBtn.getText();
            }
            q = new age25to40(voterAge, candidate, gender, q1, q2);
            poll.add(q);

        }

        //move to panel one - new voter or admin
        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
        //clear inputs

        p4Answer1TF.setText("");
        p4Answer2TF.setText("");
        ageGroup.clearSelection();
        panel4Group.clearSelection();


    }//GEN-LAST:event_p4SubmitBtnActionPerformed

    private void p5SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5SubmitBtnActionPerformed
        // TODO add your handling code here:
        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q;

        String candidate = (String) p5candidateComboBox.getSelectedItem();

        if (voterAge.equals("41 - 65")) {
            q1 = p5Answer1TF.getText();
            q2 = p5Answer2TF.getText();

            //convert gender group btn to String
            if (p5maleBtn.isSelected()) {
                gender = p5maleBtn.getText();
            }
            if (p5femaleBtn.isSelected()) {
                gender = p5maleBtn.getText();
            }
            q = new age40to65(voterAge, candidate, gender, q1, q2);
            poll.add(q);

        }

        //move to panel one - new voter or admin
        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
        //clear inputs

        p5Answer1TF.setText("");
        p5Answer2TF.setText("");
        ageGroup.clearSelection();
        panel5Group.clearSelection();
    }//GEN-LAST:event_p5SubmitBtnActionPerformed

    private void p6SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q;

        String candidate = (String) p6candidateComboBox.getSelectedItem();

        if (voterAge.equals("> 65")) {
            q1 = p6Answer1TF.getText();
            q2 = p6Answer2TF.getText();

            //convert gender group btn to String
            if (p6maleBtn.isSelected()) {
                gender = p6maleBtn.getText();
            }
            if (p6femaleBtn.isSelected()) {
                gender = p6maleBtn.getText();
            }
            q = new ageOver65(voterAge, candidate, gender, q1, q2);
            poll.add(q);

        }

        //move to panel one - new voter or admin
        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
        //clear inputs

        p6Answer1TF.setText("");
        p6Answer2TF.setText("");
        ageGroup.clearSelection();
        panel6Group.clearSelection();
    }//GEN-LAST:event_p6SubmitBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        panelOne.setVisible(true);
        panelTwo.setVisible(false);
        panelThree.setVisible(false);
        panelFour.setVisible(false);
        panelFive.setVisible(false);
        panelSix.setVisible(false);
        panelSeven.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void p3Answer2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3Answer2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3Answer2TFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //FileWriter fw;
        //BufferedWriter bw;
        
        try {
            outFile = new File("votes.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            //fw = new FileWriter(outFile, true);
            //bw = new BufferedWriter(fw);
            
            oStream.writeObject(poll);
            
            oStream.close();
         
//            for (Question x : poll) {
//                
//                if (x instanceof age18to25) {
//                    age18to25 myB1 = (age18to25) x;
//                    bw.write(myB1.printDetails());
//                    bw.newLine();
//                } else if (x instanceof age25to40) {
//                    age25to40 myB1 = (age25to40) x;
//                    bw.write(myB1.printDetails());
//                    bw.newLine();
//                } else if (x instanceof age40to65) {
//                    age40to65 myB1 = (age40to65) x;
//                    bw.write(myB1.printDetails());
//                    bw.newLine();
//                } else if (x instanceof ageOver65) {
//                    ageOver65 myB1 = (ageOver65) x;
//                    bw.write(myB1.printDetails());
//                    bw.newLine();
//                } else {
//                    bw.write(x.printDetails());
//                    bw.newLine();
//                }
            }
            
//            bw.close();
            
         catch (IOException e) {
            System.out.println("EThere was an error writing to file: " + e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed
     
    
       //Load and Save
      // private void saveBTN(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
   
                                      

    //private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PollGui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminUserBtn;
    private javax.swing.ButtonGroup ageGroup;
    private javax.swing.JLabel ageGroupLbl;
    private javax.swing.JRadioButton ageGrp1Btn;
    private javax.swing.JRadioButton ageGrp2Btn;
    private javax.swing.JRadioButton ageGrp3Btn;
    private javax.swing.JRadioButton ageGrp4Btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel mainHeadingLbl;
    private javax.swing.JLabel mainHeadingLbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField p3Answer1TF;
    private javax.swing.JTextField p3Answer2TF;
    private javax.swing.JLabel p3Q1Lbl;
    private javax.swing.JLabel p3Q2Lbl;
    private javax.swing.JButton p3SubmitBtn;
    private javax.swing.JComboBox<String> p3candidateComboBox;
    private javax.swing.JRadioButton p3femaleBtn;
    private javax.swing.JLabel p3mainHeadingLbl;
    private javax.swing.JRadioButton p3maleBtn;
    private javax.swing.JTextField p4Answer1TF;
    private javax.swing.JTextField p4Answer2TF;
    private javax.swing.JLabel p4Q1Lbl;
    private javax.swing.JLabel p4Q2Lbl;
    private javax.swing.JButton p4SubmitBtn;
    private javax.swing.JComboBox<String> p4candidateComboBox;
    private javax.swing.JRadioButton p4femaleBtn;
    private javax.swing.JLabel p4mainHeadingLbl;
    private javax.swing.JRadioButton p4maleBtn;
    private javax.swing.JTextField p5Answer1TF;
    private javax.swing.JTextField p5Answer2TF;
    private javax.swing.JLabel p5Q1Lbl;
    private javax.swing.JLabel p5Q2Lbl;
    private javax.swing.JButton p5SubmitBtn;
    private javax.swing.JComboBox<String> p5candidateComboBox;
    private javax.swing.JRadioButton p5femaleBtn;
    private javax.swing.JLabel p5mainHeadingLbl;
    private javax.swing.JRadioButton p5maleBtn;
    private javax.swing.JTextField p6Answer1TF;
    private javax.swing.JTextField p6Answer2TF;
    private javax.swing.JLabel p6Q1Lbl;
    private javax.swing.JLabel p6Q2Lbl;
    private javax.swing.JButton p6SubmitBtn;
    private javax.swing.JComboBox<String> p6candidateComboBox;
    private javax.swing.JRadioButton p6femaleBtn;
    private javax.swing.JLabel p6mainHeadingLbl;
    private javax.swing.JRadioButton p6maleBtn;
    private javax.swing.JLabel p7mainHeadingLbl;
    private javax.swing.ButtonGroup panel3Group;
    private javax.swing.ButtonGroup panel4Group;
    private javax.swing.ButtonGroup panel5Group;
    private javax.swing.ButtonGroup panel6Group;
    private javax.swing.JPanel panelFive;
    private javax.swing.JPanel panelFour;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel panelSeven;
    private javax.swing.JPanel panelSix;
    private javax.swing.JPanel panelThree;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel userTypeLbl;
    private javax.swing.JButton voterUserBtn;
    // End of variables declaration//GEN-END:variables

}
