/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapplication;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *  Date from 13/11/18 to 07/12/18
 * @author mark kelly, Lorcan Murray & Kevin Brennan
 * students numbers 17138311, 16105834 & 16149823
 */
public class PollGui extends javax.swing.JFrame {

    ArrayList<Question> poll;
    
    private int countGroup1 = 0;
    private int countGroup2 = 0;
    private int countGroup3 = 0;
    private int countGroup4 = 0;
    
    private int male = 0; 
    private int female = 0;

    /**
     * Creates new form PollGui
     */
    public PollGui() {
        initComponents();

        poll = new ArrayList<>();
        

        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3Group = new javax.swing.ButtonGroup();
        ageGroup = new javax.swing.ButtonGroup();
        panel6Group = new javax.swing.ButtonGroup();
        panel5Group = new javax.swing.ButtonGroup();
        panel4Group = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panelThreeAgeGr1 = new javax.swing.JPanel();
        p3mainHeadingLbl = new javax.swing.JLabel();
        p3candidateComboBox = new javax.swing.JComboBox<>();
        p3maleBtn = new javax.swing.JRadioButton();
        p3femaleBtn = new javax.swing.JRadioButton();
        p3Q1Lbl = new javax.swing.JLabel();
        p3Q2Lbl = new javax.swing.JLabel();
        p3Answer1TF = new javax.swing.JTextField();
        p3Answer2TF = new javax.swing.JTextField();
        p3SubmitBtn = new javax.swing.JButton();
        p3CandidateLbl = new javax.swing.JLabel();
        p3GenderLbl = new javax.swing.JLabel();
        p3BackBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelFourAgeGr2 = new javax.swing.JPanel();
        p4mainHeadingLbl = new javax.swing.JLabel();
        p4candidateComboBox = new javax.swing.JComboBox<>();
        p4maleBtn = new javax.swing.JRadioButton();
        p4femaleBtn = new javax.swing.JRadioButton();
        p4Q1Lbl = new javax.swing.JLabel();
        p4Q2Lbl = new javax.swing.JLabel();
        p4Answer1TF = new javax.swing.JTextField();
        p4Answer2TF = new javax.swing.JTextField();
        p4SubmitBtn = new javax.swing.JButton();
        p4CandidateLbl = new javax.swing.JLabel();
        p4GenderLbl = new javax.swing.JLabel();
        p4BackBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelFiveAgeGr3 = new javax.swing.JPanel();
        p5mainHeadingLbl = new javax.swing.JLabel();
        p5candidateComboBox = new javax.swing.JComboBox<>();
        p5maleBtn = new javax.swing.JRadioButton();
        p5femaleBtn = new javax.swing.JRadioButton();
        p5Q1Lbl = new javax.swing.JLabel();
        p5Q2Lbl = new javax.swing.JLabel();
        p5Answer1TF = new javax.swing.JTextField();
        p5Answer2TF = new javax.swing.JTextField();
        p5SubmitBtn = new javax.swing.JButton();
        p5BackBtn = new javax.swing.JButton();
        p5GenderLbl = new javax.swing.JLabel();
        p5CandidateLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelSixAgeGr4 = new javax.swing.JPanel();
        p6mainHeadingLbl = new javax.swing.JLabel();
        p6candidateComboBox = new javax.swing.JComboBox<>();
        p6maleBtn = new javax.swing.JRadioButton();
        p6femaleBtn = new javax.swing.JRadioButton();
        p6Q1Lbl = new javax.swing.JLabel();
        p6Q2Lbl = new javax.swing.JLabel();
        p6Answer1TF = new javax.swing.JTextField();
        p6Answer2TF = new javax.swing.JTextField();
        p6SubmitBtn = new javax.swing.JButton();
        p6BackBtn = new javax.swing.JButton();
        p6CandidateLbl = new javax.swing.JLabel();
        p6GenderLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelSevenAgeSelection = new javax.swing.JPanel();
        p7mainHeadingLbl = new javax.swing.JLabel();
        ageGrp1Btn = new javax.swing.JRadioButton();
        ageGrp2Btn = new javax.swing.JRadioButton();
        ageGrp3Btn = new javax.swing.JRadioButton();
        ageGrp4Btn = new javax.swing.JRadioButton();
        ageGroupLbl = new javax.swing.JLabel();
        ageBackBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        panelOneUserType = new javax.swing.JPanel();
        mainHeadingLbl = new javax.swing.JLabel();
        userTypeLbl = new javax.swing.JLabel();
        adminUserBtn = new javax.swing.JButton();
        voterUserBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panelTwoAdmin = new javax.swing.JPanel();
        mainHeadingLbl1 = new javax.swing.JLabel();
        loadBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        adminBackBTN = new javax.swing.JButton();
        adminLbl = new javax.swing.JLabel();
        ageStatBtn = new javax.swing.JButton();
        genderStatBtn = new javax.swing.JButton();
        statLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setPreferredSize(new java.awt.Dimension(806, 300));
        mainPanel.setLayout(new java.awt.CardLayout());

        panelThreeAgeGr1.setPreferredSize(new java.awt.Dimension(1006, 579));

        p3mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        p3mainHeadingLbl.setText("Election Application 2018");

        p3candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada4" }));

        panel3Group.add(p3maleBtn);
        p3maleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p3maleBtn.setText("Male");
        p3maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p3maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3maleBtnActionPerformed(evt);
            }
        });

        panel3Group.add(p3femaleBtn);
        p3femaleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p3femaleBtn.setText("Female");
        p3femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p3femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3femaleBtnActionPerformed(evt);
            }
        });

        p3Q1Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p3Q1Lbl.setText("Q1: Is this your first time voting?");

        p3Q2Lbl.setBackground(new java.awt.Color(0, 0, 0));
        p3Q2Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p3Q2Lbl.setText("Q2: Have you lived abroad (> 3 month period)?");

        p3Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p3Answer1TF.setPreferredSize(new java.awt.Dimension(653, 28));
        p3Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3Answer1TFActionPerformed(evt);
            }
        });

        p3Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p3Answer2TF.setForeground(new java.awt.Color(255, 0, 0));
        p3Answer2TF.setPreferredSize(new java.awt.Dimension(653, 28));
        p3Answer2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3Answer2TFActionPerformed(evt);
            }
        });

        p3SubmitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p3SubmitBtn.setText("Submit");
        p3SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p3SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3SubmitBtnActionPerformed(evt);
            }
        });

        p3CandidateLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p3CandidateLbl.setText("Select a candidate:");

        p3GenderLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p3GenderLbl.setText("Gender?");

        p3BackBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p3BackBtn.setText("Back");
        p3BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3BackBtnActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelThreeAgeGr1Layout = new javax.swing.GroupLayout(panelThreeAgeGr1);
        panelThreeAgeGr1.setLayout(panelThreeAgeGr1Layout);
        panelThreeAgeGr1Layout.setHorizontalGroup(
            panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p3Q1Lbl)
                    .addComponent(p3mainHeadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                        .addComponent(p3CandidateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                        .addComponent(p3maleBtn)
                        .addGap(32, 32, 32)
                        .addComponent(p3femaleBtn))
                    .addComponent(p3GenderLbl)
                    .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                        .addComponent(p3SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p3BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p3Answer2TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(p3Answer1TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(p3Q2Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelThreeAgeGr1Layout.setVerticalGroup(
            panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(p3mainHeadingLbl))
                    .addGroup(panelThreeAgeGr1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3CandidateLbl)
                    .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(p3GenderLbl)
                .addGap(18, 18, 18)
                .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3maleBtn)
                    .addComponent(p3femaleBtn))
                .addGap(28, 28, 28)
                .addComponent(p3Q1Lbl)
                .addGap(18, 18, 18)
                .addComponent(p3Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(p3Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelThreeAgeGr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3SubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        mainPanel.add(panelThreeAgeGr1, "card4");

        p4mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        p4mainHeadingLbl.setText("Election Application 2018");

        p4candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel4Group.add(p4maleBtn);
        p4maleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p4maleBtn.setText("Male");
        p4maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4maleBtnActionPerformed(evt);
            }
        });

        panel4Group.add(p4femaleBtn);
        p4femaleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p4femaleBtn.setText("Female");
        p4femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4femaleBtnActionPerformed(evt);
            }
        });

        p4Q1Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p4Q1Lbl.setText("Q1: Have you voted in previous presidential elections?");

        p4Q2Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p4Q2Lbl.setText("Q2: What is your marital status?");

        p4Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p4Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4Answer1TFActionPerformed(evt);
            }
        });

        p4Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p4Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p4SubmitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p4SubmitBtn.setText("Submit");
        p4SubmitBtn.setBorder(p3BackBtn.getBorder());
        p4SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p4SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4SubmitBtnActionPerformed(evt);
            }
        });

        p4CandidateLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p4CandidateLbl.setText("Select a Candidate: ");

        p4GenderLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p4GenderLbl.setText("Gender?");

        p4BackBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p4BackBtn.setText("Back");
        p4BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4BackBtnActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelFourAgeGr2Layout = new javax.swing.GroupLayout(panelFourAgeGr2);
        panelFourAgeGr2.setLayout(panelFourAgeGr2Layout);
        panelFourAgeGr2Layout.setHorizontalGroup(
            panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p4GenderLbl)
                    .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                        .addComponent(p4SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p4BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p4Q2Lbl)
                    .addComponent(p4Q1Lbl)
                    .addComponent(p4mainHeadingLbl)
                    .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                        .addComponent(p4maleBtn)
                        .addGap(32, 32, 32)
                        .addComponent(p4femaleBtn))
                    .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                        .addComponent(p4CandidateLbl)
                        .addGap(24, 24, 24)
                        .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p4Answer2TF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p4Answer1TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelFourAgeGr2Layout.setVerticalGroup(
            panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(p4mainHeadingLbl))
                    .addGroup(panelFourAgeGr2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4CandidateLbl))
                .addGap(28, 28, 28)
                .addComponent(p4GenderLbl)
                .addGap(18, 18, 18)
                .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4maleBtn)
                    .addComponent(p4femaleBtn))
                .addGap(31, 31, 31)
                .addComponent(p4Q1Lbl)
                .addGap(18, 18, 18)
                .addComponent(p4Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p4Q2Lbl)
                .addGap(18, 18, 18)
                .addComponent(p4Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelFourAgeGr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        mainPanel.add(panelFourAgeGr2, "card5");

        p5mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        p5mainHeadingLbl.setText("Election Application 2018");

        p5candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel5Group.add(p5maleBtn);
        p5maleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p5maleBtn.setText("Male");
        p5maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5maleBtnActionPerformed(evt);
            }
        });

        panel5Group.add(p5femaleBtn);
        p5femaleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p5femaleBtn.setText("Female");
        p5femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5femaleBtnActionPerformed(evt);
            }
        });

        p5Q1Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p5Q1Lbl.setText("Q1: Do you have any children?");

        p5Q2Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p5Q2Lbl.setText("Q2: If you own a car, what type of of car is it (diesel / petrol / hybrid / electric)?");

        p5Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p5Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5Answer1TFActionPerformed(evt);
            }
        });

        p5Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p5Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p5SubmitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p5SubmitBtn.setText("Submit");
        p5SubmitBtn.setBorder(p3BackBtn.getBorder());
        p5SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p5SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5SubmitBtnActionPerformed(evt);
            }
        });

        p5BackBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p5BackBtn.setText("Back");
        p5BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5BackBtnActionPerformed(evt);
            }
        });

        p5GenderLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p5GenderLbl.setText("Gender");

        p5CandidateLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p5CandidateLbl.setText("Select a Candidate");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelFiveAgeGr3Layout = new javax.swing.GroupLayout(panelFiveAgeGr3);
        panelFiveAgeGr3.setLayout(panelFiveAgeGr3Layout);
        panelFiveAgeGr3Layout.setHorizontalGroup(
            panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                        .addComponent(p5CandidateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                        .addComponent(p5SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p5BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p5Q1Lbl)
                    .addComponent(p5mainHeadingLbl)
                    .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p5Answer1TF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p5Answer2TF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p5Q2Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                        .addComponent(p5maleBtn)
                        .addGap(48, 48, 48)
                        .addComponent(p5femaleBtn))
                    .addComponent(p5GenderLbl))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelFiveAgeGr3Layout.setVerticalGroup(
            panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(p5mainHeadingLbl))
                    .addGroup(panelFiveAgeGr3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5CandidateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(p5GenderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5maleBtn)
                    .addComponent(p5femaleBtn))
                .addGap(43, 43, 43)
                .addComponent(p5Q1Lbl)
                .addGap(18, 18, 18)
                .addComponent(p5Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p5Q2Lbl)
                .addGap(18, 18, 18)
                .addComponent(p5Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelFiveAgeGr3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        mainPanel.add(panelFiveAgeGr3, "card6");

        p6mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        p6mainHeadingLbl.setText("Election Application 2018");

        p6candidateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Peter Casey", "Gavin Duffy", "Joan Freeman", "Sean Gallagher", "Michael D Higgins", "Liadh Ni Riada" }));

        panel6Group.add(p6maleBtn);
        p6maleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p6maleBtn.setText("Male");
        p6maleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p6maleBtn.setContentAreaFilled(false);
        p6maleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6maleBtnActionPerformed(evt);
            }
        });

        panel6Group.add(p6femaleBtn);
        p6femaleBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p6femaleBtn.setText("Female");
        p6femaleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p6femaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6femaleBtnActionPerformed(evt);
            }
        });

        p6Q1Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p6Q1Lbl.setText("Q1: Who did you vote for in the previous presidential election?");

        p6Q2Lbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p6Q2Lbl.setText("Q2: Do you have a smart phone?");

        p6Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Answer1TF.setForeground(new java.awt.Color(255, 0, 0));
        p6Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6Answer1TFActionPerformed(evt);
            }
        });

        p6Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p6Answer2TF.setForeground(new java.awt.Color(255, 0, 0));

        p6SubmitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p6SubmitBtn.setText("Submit");
        p6SubmitBtn.setBorder(p3BackBtn.getBorder());
        p6SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6SubmitBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        p6SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6SubmitBtnActionPerformed(evt);
            }
        });

        p6BackBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        p6BackBtn.setText("Back");
        p6BackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6BackBtnActionPerformed(evt);
            }
        });

        p6CandidateLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p6CandidateLbl.setText("Select a Candidate");

        p6GenderLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p6GenderLbl.setText("Gender");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSixAgeGr4Layout = new javax.swing.GroupLayout(panelSixAgeGr4);
        panelSixAgeGr4.setLayout(panelSixAgeGr4Layout);
        panelSixAgeGr4Layout.setHorizontalGroup(
            panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p6GenderLbl)
                    .addComponent(p6Q2Lbl)
                    .addComponent(p6mainHeadingLbl)
                    .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                        .addComponent(p6maleBtn)
                        .addGap(33, 33, 33)
                        .addComponent(p6femaleBtn))
                    .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                        .addComponent(p6CandidateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                        .addComponent(p6SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p6BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p6Answer2TF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p6Answer1TF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p6Q1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelSixAgeGr4Layout.setVerticalGroup(
            panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(p6mainHeadingLbl))
                    .addGroup(panelSixAgeGr4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6CandidateLbl)
                    .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(p6GenderLbl)
                .addGap(18, 18, 18)
                .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6maleBtn)
                    .addComponent(p6femaleBtn))
                .addGap(34, 34, 34)
                .addComponent(p6Q1Lbl)
                .addGap(18, 18, 18)
                .addComponent(p6Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p6Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p6Answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelSixAgeGr4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6SubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        mainPanel.add(panelSixAgeGr4, "card7");

        p7mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        p7mainHeadingLbl.setText("Election Application 2018");

        ageGroup.add(ageGrp1Btn);
        ageGrp1Btn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ageGrp1Btn.setText("18 - 25");
        ageGrp1Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp1BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp2Btn);
        ageGrp2Btn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ageGrp2Btn.setText("26 - 40");
        ageGrp2Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp2BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp3Btn);
        ageGrp3Btn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ageGrp3Btn.setText("41 - 65");
        ageGrp3Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp3BtnActionPerformed(evt);
            }
        });

        ageGroup.add(ageGrp4Btn);
        ageGrp4Btn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ageGrp4Btn.setText("> 65");
        ageGrp4Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ageGrp4Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageGrp4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGrp4BtnActionPerformed(evt);
            }
        });

        ageGroupLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ageGroupLbl.setText("Select your age category");

        ageBackBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ageBackBtn.setText("Back");
        ageBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageBackBtnActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSevenAgeSelectionLayout = new javax.swing.GroupLayout(panelSevenAgeSelection);
        panelSevenAgeSelection.setLayout(panelSevenAgeSelectionLayout);
        panelSevenAgeSelectionLayout.setHorizontalGroup(
            panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                .addGroup(panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                                .addComponent(ageGrp1Btn)
                                .addGap(112, 112, 112)
                                .addComponent(ageGrp2Btn)
                                .addGap(108, 108, 108)
                                .addComponent(ageGrp3Btn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSevenAgeSelectionLayout.createSequentialGroup()
                                .addComponent(ageGroupLbl)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageGrp4Btn)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSevenAgeSelectionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ageBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        panelSevenAgeSelectionLayout.setVerticalGroup(
            panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                .addGroup(panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(p7mainHeadingLbl))
                    .addGroup(panelSevenAgeSelectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addComponent(ageGroupLbl)
                .addGap(74, 74, 74)
                .addGroup(panelSevenAgeSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGrp1Btn)
                    .addComponent(ageGrp2Btn)
                    .addComponent(ageGrp3Btn)
                    .addComponent(ageGrp4Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(ageBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(panelSevenAgeSelection, "card8");

        panelOneUserType.setPreferredSize(new java.awt.Dimension(1006, 560));

        mainHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mainHeadingLbl.setText("Election Application 2018");

        userTypeLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userTypeLbl.setText("User type:");

        adminUserBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminUserBtn.setText("Admin");
        adminUserBtn.setBorder(p6BackBtn.getBorder());
        adminUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminUserBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        adminUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserBtnActionPerformed(evt);
            }
        });

        voterUserBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        voterUserBtn.setText("Voter");
        voterUserBtn.setBorder(p3BackBtn.getBorder());
        voterUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voterUserBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        voterUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterUserBtnActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelOneUserTypeLayout = new javax.swing.GroupLayout(panelOneUserType);
        panelOneUserType.setLayout(panelOneUserTypeLayout);
        panelOneUserTypeLayout.setHorizontalGroup(
            panelOneUserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                .addGroup(panelOneUserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(mainHeadingLbl))
                    .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(adminUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(voterUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOneUserTypeLayout.createSequentialGroup()
                .addComponent(userTypeLbl)
                .addGap(359, 359, 359))
        );
        panelOneUserTypeLayout.setVerticalGroup(
            panelOneUserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                .addGroup(panelOneUserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(mainHeadingLbl))
                    .addGroup(panelOneUserTypeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127)
                .addComponent(userTypeLbl)
                .addGap(18, 18, 18)
                .addGroup(panelOneUserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voterUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(300, 300, 300))
        );

        mainPanel.add(panelOneUserType, "card2");

        mainHeadingLbl1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        mainHeadingLbl1.setText("Election Application 2018");

        loadBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        loadBTN.setText("Load");
        loadBTN.setBorder(p3BackBtn.getBorder());
        loadBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.setBorder(p3BackBtn.getBorder());
        saveBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        viewBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        viewBTN.setText("View");
        viewBTN.setBorder(p3BackBtn.getBorder());
        viewBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        adminBackBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminBackBTN.setText("Back");
        adminBackBTN.setBorder(p3BackBtn.getBorder());
        adminBackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminBackBTN.setPreferredSize(new java.awt.Dimension(150, 50));
        adminBackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackBTNActionPerformed(evt);
            }
        });

        adminLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adminLbl.setText("Administration Panel:");

        ageStatBtn.setText("Age");
        ageStatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageStatBtn.setMaximumSize(new java.awt.Dimension(83, 29));
        ageStatBtn.setMinimumSize(new java.awt.Dimension(83, 29));
        ageStatBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        ageStatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageStatBtnActionPerformed(evt);
            }
        });

        genderStatBtn.setText("Gender");
        genderStatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genderStatBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        genderStatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderStatBtnActionPerformed(evt);
            }
        });

        statLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        statLbl.setText("View statistics for this session:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2610-128.jpg"))); // NOI18N

        javax.swing.GroupLayout panelTwoAdminLayout = new javax.swing.GroupLayout(panelTwoAdmin);
        panelTwoAdmin.setLayout(panelTwoAdminLayout);
        panelTwoAdminLayout.setHorizontalGroup(
            panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoAdminLayout.createSequentialGroup()
                .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTwoAdminLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTwoAdminLayout.createSequentialGroup()
                                .addComponent(ageStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statLbl)))
                    .addGroup(panelTwoAdminLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(adminLbl)))
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTwoAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTwoAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminBackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTwoAdminLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainHeadingLbl1)
                        .addGap(89, 89, 89))))
        );
        panelTwoAdminLayout.setVerticalGroup(
            panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoAdminLayout.createSequentialGroup()
                .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTwoAdminLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(mainHeadingLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTwoAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(adminLbl)
                .addGap(44, 44, 44)
                .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminBackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(statLbl)
                .addGap(18, 18, 18)
                .addGroup(panelTwoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        mainPanel.add(panelTwoAdmin, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserBtnActionPerformed
        // TODO add your handling code here:
        int pin = Integer.parseInt(JOptionPane.showInputDialog("Please enter your pin","Staff Pin Number"));
        
        if(pin==311| pin==823 | pin==834 ){
            panelOneUserType.setVisible(false);
            panelTwoAdmin.setVisible(true);
            panelThreeAgeGr1.setVisible(false);
            panelFourAgeGr2.setVisible(false);
            panelFiveAgeGr3.setVisible(false);
            panelSixAgeGr4.setVisible(false);
            panelSevenAgeSelection.setVisible(false);
        }
        else{
        JOptionPane.showMessageDialog(null,"Sorry, Pin is invalid");
    }
    }//GEN-LAST:event_adminUserBtnActionPerformed

    private void voterUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterUserBtnActionPerformed
        // TODO add your handling code here:
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(true);
    }//GEN-LAST:event_voterUserBtnActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        //@reference VehicleApp OOP class sample
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try {
            inFile = new File("votes.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream); 
            
            poll = (ArrayList<Question>) oStream.readObject();
            
           oStream.close(); 

        }

         catch (IOException e) {
            System.out.println("There was an error writing to file: " + e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PollGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadBTNActionPerformed

    private void p3Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3Answer1TFActionPerformed

    private void p4Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4Answer1TFActionPerformed

    private void p5Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5Answer1TFActionPerformed

    private void p6Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6Answer1TFActionPerformed

    private void ageGrp1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp1BtnActionPerformed
        // TODO add your handling code here:
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(true);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        
        countGroup1 = countGroup1+1;
    }//GEN-LAST:event_ageGrp1BtnActionPerformed

    private void ageGrp2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp2BtnActionPerformed
        // TODO add your handling code here:
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(true);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        
        countGroup2 = countGroup2+1;
    }//GEN-LAST:event_ageGrp2BtnActionPerformed

    private void ageGrp3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp3BtnActionPerformed
        // TODO add your handling code here:
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(true);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        
        countGroup3 = countGroup3+1;
    }//GEN-LAST:event_ageGrp3BtnActionPerformed

    private void ageGrp4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGrp4BtnActionPerformed
        // TODO add your handling code here:
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(true);
        panelSevenAgeSelection.setVisible(false);
        
        countGroup4 = countGroup4+1;
    }//GEN-LAST:event_ageGrp4BtnActionPerformed

    private void p3SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;
        

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q = null;
        
        String candidate = (String) p3candidateComboBox.getSelectedItem();

        if (voterAge.equals("18 - 25")) {
            q1 = p3Answer1TF.getText();
            q2 = p3Answer2TF.getText();
          

            //convert gender group btn to String
            if (p3maleBtn.isSelected()) {
                gender = p3maleBtn.getText();
            }
            if (p3femaleBtn.isSelected()) {
                gender = p3femaleBtn.getText();
            }
            q = new age18to25(voterAge, candidate, gender, q1, q2);
            
        }
        if(q1.equals("")|q2.equals("")|candidate.equals("")){
            JOptionPane.showMessageDialog(null,"Please answer all questions");
        
    }
        else if(p3maleBtn.isSelected()|p3femaleBtn.isSelected()){
            
        poll.add(q);

        //move to panel one - new voter or admin
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        //clear inputs
        p3Answer1TF.setText("");
        p3Answer2TF.setText("");
        ageGroup.clearSelection();
        panel3Group.clearSelection();
        }
        else{JOptionPane.showMessageDialog(null,"Please select a gender");
        
        }


    }//GEN-LAST:event_p3SubmitBtnActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        // TODO add your handling code here:
        for (Question x : poll) {

            if (x instanceof age18to25) {
                age18to25 myA1 = (age18to25) x;
                JOptionPane.showMessageDialog(null, myA1.printDetails());

            } else if (x instanceof age25to40) {
                age25to40 myA2 = (age25to40) x;
                JOptionPane.showMessageDialog(null, myA2.printDetails());

            } else if (x instanceof age40to65) {
                age40to65 myA3 = (age40to65) x;
                JOptionPane.showMessageDialog(null, myA3.printDetails());

            } else if (x instanceof ageOver65) {
                ageOver65 myA4 = (ageOver65) x;
                JOptionPane.showMessageDialog(null, myA4.printDetails());
                
            } else {
                JOptionPane.showMessageDialog(null, x.printDetails());
            }
        }
    }//GEN-LAST:event_viewBTNActionPerformed

    private void p4SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q = null;

        String candidate = (String) p4candidateComboBox.getSelectedItem();

        if (voterAge.equals("26 - 40")) {
            q1 = p4Answer1TF.getText();
            q2 = p4Answer2TF.getText();

            //convert gender group btn to String
            if (p4maleBtn.isSelected()) {
                gender = p4maleBtn.getText();
            }
            if (p4femaleBtn.isSelected()) {
                gender = p4femaleBtn.getText();
            }
            q = new age25to40(voterAge, candidate, gender, q1, q2);
        }
            if(q1.equals("")|q2.equals("")|candidate.equals("")){
            JOptionPane.showMessageDialog(null,"Please answer all questions");
        
    }
        else if(p4maleBtn.isSelected()|p4femaleBtn.isSelected()){
            
        poll.add(q);

        

        //move to panel one - new voter or admin
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        //clear inputs

        p4Answer1TF.setText("");
        p4Answer2TF.setText("");
        ageGroup.clearSelection();
        panel4Group.clearSelection();
        }
        else{JOptionPane.showMessageDialog(null,"Please select a gender");
        
        }


    }//GEN-LAST:event_p4SubmitBtnActionPerformed

    private void p5SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5SubmitBtnActionPerformed
        // TODO add your handling code here:
        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q=null;

        String candidate = (String) p5candidateComboBox.getSelectedItem();

        if (voterAge.equals("41 - 65")) {
            q1 = p5Answer1TF.getText();
            q2 = p5Answer2TF.getText();

            //convert gender group btn to String
            if (p5maleBtn.isSelected()) {
                gender = p5maleBtn.getText();
            }
            if (p5femaleBtn.isSelected()) {
                gender = p5femaleBtn.getText();
            }
            q = new age40to65(voterAge, candidate, gender, q1, q2);
        }
            if(q1.equals("")|q2.equals("")|candidate.equals("")){
            JOptionPane.showMessageDialog(null,"Please answer all questions");
        
    }
        else if(p5maleBtn.isSelected()|p5femaleBtn.isSelected()){
            
        poll.add(q);

        //move to panel one - new voter or admin
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        //clear inputs

        p5Answer1TF.setText("");
        p5Answer2TF.setText("");
        ageGroup.clearSelection();
        panel5Group.clearSelection();
        
               }
        else{JOptionPane.showMessageDialog(null,"Please select a gender");
        
        }
    }//GEN-LAST:event_p5SubmitBtnActionPerformed

    private void p6SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6SubmitBtnActionPerformed
        // TODO add your handling code here:

        String q1 = "";
        String q2 = "";
        String voterAge = null;
        String gender = null;

        //convert age group btn to String
        if (ageGrp1Btn.isSelected()) {
            voterAge = ageGrp1Btn.getText();
        }
        if (ageGrp2Btn.isSelected()) {
            voterAge = ageGrp2Btn.getText();
        }
        if (ageGrp3Btn.isSelected()) {
            voterAge = ageGrp3Btn.getText();
        }
        if (ageGrp4Btn.isSelected()) {
            voterAge = ageGrp4Btn.getText();
        }

        Question q=null;

        String candidate = (String) p6candidateComboBox.getSelectedItem();

        if (voterAge.equals("> 65")) {
            q1 = p6Answer1TF.getText();
            q2 = p6Answer2TF.getText();

            //convert gender group btn to String
            if (p6maleBtn.isSelected()) {
                gender = p6maleBtn.getText();
            }
            if (p6femaleBtn.isSelected()) {
                gender = p6femaleBtn.getText();
            }
            q = new ageOver65(voterAge, candidate, gender, q1, q2);
 }
            if(q1.equals("")|q2.equals("")|candidate.equals("")){
            JOptionPane.showMessageDialog(null,"Please answer all questions");
        
    }
        else if(p6maleBtn.isSelected()|p6femaleBtn.isSelected()){
            
        poll.add(q);


        //move to panel one - new voter or admin
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
        //clear inputs

        p6Answer1TF.setText("");
        p6Answer2TF.setText("");
        ageGroup.clearSelection();
        panel6Group.clearSelection();
        
               
               }
        else{JOptionPane.showMessageDialog(null,"Please select a gender");
        
        }
    }//GEN-LAST:event_p6SubmitBtnActionPerformed

    private void adminBackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackBTNActionPerformed
        // TODO add your handling code here:
        
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
    }//GEN-LAST:event_adminBackBTNActionPerformed

    private void p3Answer2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3Answer2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3Answer2TFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        //@reference VehicleApp OOP class sample
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        
        try {
            outFile = new File("votes.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            
            oStream.writeObject(poll);
            
            oStream.close();

            }

            
         catch (IOException e) {
            System.out.println("EThere was an error writing to file: " + e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void p4femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4femaleBtnActionPerformed
        // TODO add your handling code here:
        female = female +1;
    }//GEN-LAST:event_p4femaleBtnActionPerformed

    private void ageBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageBackBtnActionPerformed
        // Back button for age group selection   
        panelOneUserType.setVisible(true);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(false);
    }//GEN-LAST:event_ageBackBtnActionPerformed

    private void p6BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6BackBtnActionPerformed
        // Back button for age 65+
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(true);
    }//GEN-LAST:event_p6BackBtnActionPerformed

    private void p4BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4BackBtnActionPerformed
        // Back button for age group 25+
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(true);
    }//GEN-LAST:event_p4BackBtnActionPerformed

    private void p3BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3BackBtnActionPerformed
        // Back button for age group 18+
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(true);
    }//GEN-LAST:event_p3BackBtnActionPerformed

    private void p5BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5BackBtnActionPerformed
        // Back button for age group 41+
        panelOneUserType.setVisible(false);
        panelTwoAdmin.setVisible(false);
        panelThreeAgeGr1.setVisible(false);
        panelFourAgeGr2.setVisible(false);
        panelFiveAgeGr3.setVisible(false);
        panelSixAgeGr4.setVisible(false);
        panelSevenAgeSelection.setVisible(true);
    }//GEN-LAST:event_p5BackBtnActionPerformed

    private void ageStatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageStatBtnActionPerformed
        // Dislays session statistics on number of votes
        JOptionPane.showMessageDialog(null,"NUMBER OF VOTES PER AGE GROUP: \n\n18 to 25: "+countGroup1+"\n26 to 40: "+countGroup2+"\n41 to 64: "+countGroup3+"\n65 or over: "+countGroup4);
    }//GEN-LAST:event_ageStatBtnActionPerformed

    private void p3maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3maleBtnActionPerformed
        // TODO add your handling code here:
        male = male +1;
    }//GEN-LAST:event_p3maleBtnActionPerformed

    private void p3femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3femaleBtnActionPerformed
        // TODO add your handling code here:
        female = female +1;
    }//GEN-LAST:event_p3femaleBtnActionPerformed

    private void p4maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4maleBtnActionPerformed
        // TODO add your handling code here:
        male = male +1;
    }//GEN-LAST:event_p4maleBtnActionPerformed

    private void p5maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5maleBtnActionPerformed
        // TODO add your handling code here:
        male = male +1;
    }//GEN-LAST:event_p5maleBtnActionPerformed

    private void p5femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5femaleBtnActionPerformed
        // TODO add your handling code here:
        female = female +1;
    }//GEN-LAST:event_p5femaleBtnActionPerformed

    private void p6maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6maleBtnActionPerformed
        // TODO add your handling code here:
        male = male +1;
    }//GEN-LAST:event_p6maleBtnActionPerformed

    private void p6femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6femaleBtnActionPerformed
        // TODO add your handling code here:
        female = female +1;
    }//GEN-LAST:event_p6femaleBtnActionPerformed

    private void genderStatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderStatBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Male Voters: "+male+"\n\nFemale Voters: "+female);
    }//GEN-LAST:event_genderStatBtnActionPerformed

    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PollGui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBackBTN;
    private javax.swing.JLabel adminLbl;
    private javax.swing.JButton adminUserBtn;
    private javax.swing.JButton ageBackBtn;
    private javax.swing.ButtonGroup ageGroup;
    private javax.swing.JLabel ageGroupLbl;
    private javax.swing.JRadioButton ageGrp1Btn;
    private javax.swing.JRadioButton ageGrp2Btn;
    private javax.swing.JRadioButton ageGrp3Btn;
    private javax.swing.JRadioButton ageGrp4Btn;
    private javax.swing.JButton ageStatBtn;
    private javax.swing.JButton genderStatBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel mainHeadingLbl;
    private javax.swing.JLabel mainHeadingLbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField p3Answer1TF;
    private javax.swing.JTextField p3Answer2TF;
    private javax.swing.JButton p3BackBtn;
    private javax.swing.JLabel p3CandidateLbl;
    private javax.swing.JLabel p3GenderLbl;
    private javax.swing.JLabel p3Q1Lbl;
    private javax.swing.JLabel p3Q2Lbl;
    private javax.swing.JButton p3SubmitBtn;
    private javax.swing.JComboBox<String> p3candidateComboBox;
    private javax.swing.JRadioButton p3femaleBtn;
    private javax.swing.JLabel p3mainHeadingLbl;
    private javax.swing.JRadioButton p3maleBtn;
    private javax.swing.JTextField p4Answer1TF;
    private javax.swing.JTextField p4Answer2TF;
    private javax.swing.JButton p4BackBtn;
    private javax.swing.JLabel p4CandidateLbl;
    private javax.swing.JLabel p4GenderLbl;
    private javax.swing.JLabel p4Q1Lbl;
    private javax.swing.JLabel p4Q2Lbl;
    private javax.swing.JButton p4SubmitBtn;
    private javax.swing.JComboBox<String> p4candidateComboBox;
    private javax.swing.JRadioButton p4femaleBtn;
    private javax.swing.JLabel p4mainHeadingLbl;
    private javax.swing.JRadioButton p4maleBtn;
    private javax.swing.JTextField p5Answer1TF;
    private javax.swing.JTextField p5Answer2TF;
    private javax.swing.JButton p5BackBtn;
    private javax.swing.JLabel p5CandidateLbl;
    private javax.swing.JLabel p5GenderLbl;
    private javax.swing.JLabel p5Q1Lbl;
    private javax.swing.JLabel p5Q2Lbl;
    private javax.swing.JButton p5SubmitBtn;
    private javax.swing.JComboBox<String> p5candidateComboBox;
    private javax.swing.JRadioButton p5femaleBtn;
    private javax.swing.JLabel p5mainHeadingLbl;
    private javax.swing.JRadioButton p5maleBtn;
    private javax.swing.JTextField p6Answer1TF;
    private javax.swing.JTextField p6Answer2TF;
    private javax.swing.JButton p6BackBtn;
    private javax.swing.JLabel p6CandidateLbl;
    private javax.swing.JLabel p6GenderLbl;
    private javax.swing.JLabel p6Q1Lbl;
    private javax.swing.JLabel p6Q2Lbl;
    private javax.swing.JButton p6SubmitBtn;
    private javax.swing.JComboBox<String> p6candidateComboBox;
    private javax.swing.JRadioButton p6femaleBtn;
    private javax.swing.JLabel p6mainHeadingLbl;
    private javax.swing.JRadioButton p6maleBtn;
    private javax.swing.JLabel p7mainHeadingLbl;
    private javax.swing.ButtonGroup panel3Group;
    private javax.swing.ButtonGroup panel4Group;
    private javax.swing.ButtonGroup panel5Group;
    private javax.swing.ButtonGroup panel6Group;
    private javax.swing.JPanel panelFiveAgeGr3;
    private javax.swing.JPanel panelFourAgeGr2;
    private javax.swing.JPanel panelOneUserType;
    private javax.swing.JPanel panelSevenAgeSelection;
    private javax.swing.JPanel panelSixAgeGr4;
    private javax.swing.JPanel panelThreeAgeGr1;
    private javax.swing.JPanel panelTwoAdmin;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel statLbl;
    private javax.swing.JLabel userTypeLbl;
    private javax.swing.JButton viewBTN;
    private javax.swing.JButton voterUserBtn;
    // End of variables declaration//GEN-END:variables

}
