/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapplication;

/**
 *
 * @author markk
 */
public class PollGui extends javax.swing.JFrame {

    /**
     * Creates new form PollGui
     */
    public PollGui() {
        initComponents();
        
    panelOne.setVisible(false);
    panelTwo.setVisible(false);
    panelThree.setVisible(true);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupP3 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panelOne = new javax.swing.JPanel();
        mainHeadingLbl = new javax.swing.JLabel();
        userTypeLbl = new javax.swing.JLabel();
        adminUserBtn = new javax.swing.JButton();
        voterUserBtn = new javax.swing.JButton();
        panelTwo = new javax.swing.JPanel();
        mainHeadingLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelThree = new javax.swing.JPanel();
        p3mainHeadingLbl = new javax.swing.JLabel();
        p3candidateComboBox = new javax.swing.JComboBox<>();
        p3maleBtn = new javax.swing.JRadioButton();
        p3femaleBtn = new javax.swing.JRadioButton();
        p3Q1Lbl = new javax.swing.JLabel();
        p3Q2Lbl = new javax.swing.JLabel();
        p3Answer1TF = new javax.swing.JTextField();
        p3answer2TF = new javax.swing.JTextField();
        panelFour = new javax.swing.JPanel();
        p4mainHeadingLbl = new javax.swing.JLabel();
        p4candidateComboBox = new javax.swing.JComboBox<>();
        p4maleBtn = new javax.swing.JRadioButton();
        p4femaleBtn = new javax.swing.JRadioButton();
        p4Q1Lbl = new javax.swing.JLabel();
        p4Q2Lbl = new javax.swing.JLabel();
        p4Answer1TF = new javax.swing.JTextField();
        p4answer2TF = new javax.swing.JTextField();
        panelFive = new javax.swing.JPanel();
        p5mainHeadingLbl = new javax.swing.JLabel();
        p5candidateComboBox = new javax.swing.JComboBox<>();
        p5maleBtn = new javax.swing.JRadioButton();
        p5femaleBtn = new javax.swing.JRadioButton();
        p5Q1Lbl = new javax.swing.JLabel();
        p5Q2Lbl = new javax.swing.JLabel();
        p5Answer1TF = new javax.swing.JTextField();
        p5answer2TF = new javax.swing.JTextField();
        panelSix = new javax.swing.JPanel();
        p6mainHeadingLbl = new javax.swing.JLabel();
        p6candidateComboBox = new javax.swing.JComboBox<>();
        p6maleBtn = new javax.swing.JRadioButton();
        p6femaleBtn = new javax.swing.JRadioButton();
        p6Q1Lbl = new javax.swing.JLabel();
        p6Q2Lbl = new javax.swing.JLabel();
        p6Answer1TF = new javax.swing.JTextField();
        p6answer2TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainHeadingLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        mainHeadingLbl.setText("Election Applicaion 2018");

        userTypeLbl.setText("User type:");

        adminUserBtn.setText("Admin");
        adminUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserBtnActionPerformed(evt);
            }
        });

        voterUserBtn.setText("Voter");
        voterUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOneLayout = new javax.swing.GroupLayout(panelOne);
        panelOne.setLayout(panelOneLayout);
        panelOneLayout.setHorizontalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneLayout.createSequentialGroup()
                .addGroup(panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainHeadingLbl))
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(userTypeLbl))
                    .addGroup(panelOneLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(adminUserBtn)
                        .addGap(63, 63, 63)
                        .addComponent(voterUserBtn)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        panelOneLayout.setVerticalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainHeadingLbl)
                .addGap(114, 114, 114)
                .addComponent(userTypeLbl)
                .addGap(40, 40, 40)
                .addGroup(panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminUserBtn)
                    .addComponent(voterUserBtn))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        mainPanel.add(panelOne, "card2");

        mainHeadingLbl1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        mainHeadingLbl1.setText("Election Applicaion 2018");

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");

        jButton3.setText("Report 1");

        jButton4.setText("Report 2");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTwoLayout = new javax.swing.GroupLayout(panelTwo);
        panelTwo.setLayout(panelTwoLayout);
        panelTwoLayout.setHorizontalGroup(
            panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoLayout.createSequentialGroup()
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTwoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainHeadingLbl1))
                    .addGroup(panelTwoLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(27, 27, 27)
                        .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton2))))
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTwoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(195, 195, 195))
        );
        panelTwoLayout.setVerticalGroup(
            panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTwoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainHeadingLbl1)
                .addGap(179, 179, 179)
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(9, 9, 9)
                .addComponent(jButton5)
                .addGap(17, 17, 17)
                .addGroup(panelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        mainPanel.add(panelTwo, "card3");

        p3mainHeadingLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        p3mainHeadingLbl.setText("Election Applicaion 2018");

        p3candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupP3.add(p3maleBtn);
        p3maleBtn.setText("Male");

        buttonGroupP3.add(p3femaleBtn);
        p3femaleBtn.setText("Female");

        p3Q1Lbl.setText("Q1: Is this your first time voting?");

        p3Q2Lbl.setText("Q2: Lets pick this question another time?");

        p3Answer1TF.setText("Answer");
        p3Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3Answer1TFActionPerformed(evt);
            }
        });

        p3answer2TF.setText("Answer");

        javax.swing.GroupLayout panelThreeLayout = new javax.swing.GroupLayout(panelThree);
        panelThree.setLayout(panelThreeLayout);
        panelThreeLayout.setHorizontalGroup(
            panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3Q2Lbl)
                    .addComponent(p3Q1Lbl)
                    .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelThreeLayout.createSequentialGroup()
                        .addComponent(p3maleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p3femaleBtn))
                    .addComponent(p3answer2TF)
                    .addComponent(p3Answer1TF))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelThreeLayout.setVerticalGroup(
            panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThreeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p3mainHeadingLbl)
                .addGap(48, 48, 48)
                .addComponent(p3candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3maleBtn)
                    .addComponent(p3femaleBtn))
                .addGap(78, 78, 78)
                .addComponent(p3Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p3Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p3Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p3answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.add(panelThree, "card4");

        p4mainHeadingLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        p4mainHeadingLbl.setText("Election Applicaion 2018");

        p4candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupP3.add(p4maleBtn);
        p4maleBtn.setText("Male");

        buttonGroupP3.add(p4femaleBtn);
        p4femaleBtn.setText("Female");

        p4Q1Lbl.setText("Q1: Is this your first time voting?");

        p4Q2Lbl.setText("Q2: Lets pick this question another time?");

        p4Answer1TF.setText("Answer");
        p4Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4Answer1TFActionPerformed(evt);
            }
        });

        p4answer2TF.setText("Answer");

        javax.swing.GroupLayout panelFourLayout = new javax.swing.GroupLayout(panelFour);
        panelFour.setLayout(panelFourLayout);
        panelFourLayout.setHorizontalGroup(
            panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p4Q2Lbl)
                    .addComponent(p4Q1Lbl)
                    .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFourLayout.createSequentialGroup()
                        .addComponent(p4maleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p4femaleBtn))
                    .addComponent(p4answer2TF)
                    .addComponent(p4Answer1TF))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelFourLayout.setVerticalGroup(
            panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFourLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p4mainHeadingLbl)
                .addGap(48, 48, 48)
                .addComponent(p4candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4maleBtn)
                    .addComponent(p4femaleBtn))
                .addGap(78, 78, 78)
                .addComponent(p4Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p4Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p4Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p4answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.add(panelFour, "card5");

        p5mainHeadingLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        p5mainHeadingLbl.setText("Election Applicaion 2018");

        p5candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupP3.add(p5maleBtn);
        p5maleBtn.setText("Male");

        buttonGroupP3.add(p5femaleBtn);
        p5femaleBtn.setText("Female");

        p5Q1Lbl.setText("Q1: Is this your first time voting?");

        p5Q2Lbl.setText("Q2: Lets pick this question another time?");

        p5Answer1TF.setText("Answer");
        p5Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5Answer1TFActionPerformed(evt);
            }
        });

        p5answer2TF.setText("Answer");

        javax.swing.GroupLayout panelFiveLayout = new javax.swing.GroupLayout(panelFive);
        panelFive.setLayout(panelFiveLayout);
        panelFiveLayout.setHorizontalGroup(
            panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p5Q2Lbl)
                    .addComponent(p5Q1Lbl)
                    .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFiveLayout.createSequentialGroup()
                        .addComponent(p5maleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p5femaleBtn))
                    .addComponent(p5answer2TF)
                    .addComponent(p5Answer1TF))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelFiveLayout.setVerticalGroup(
            panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiveLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p5mainHeadingLbl)
                .addGap(48, 48, 48)
                .addComponent(p5candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5maleBtn)
                    .addComponent(p5femaleBtn))
                .addGap(78, 78, 78)
                .addComponent(p5Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p5Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.add(panelFive, "card6");

        p6mainHeadingLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        p6mainHeadingLbl.setText("Election Applicaion 2018");

        p6candidateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupP3.add(p6maleBtn);
        p6maleBtn.setText("Male");

        buttonGroupP3.add(p6femaleBtn);
        p6femaleBtn.setText("Female");

        p6Q1Lbl.setText("Q1: Is this your first time voting?");

        p6Q2Lbl.setText("Q2: Lets pick this question another time?");

        p6Answer1TF.setText("Answer");
        p6Answer1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6Answer1TFActionPerformed(evt);
            }
        });

        p6answer2TF.setText("Answer");

        javax.swing.GroupLayout panelSixLayout = new javax.swing.GroupLayout(panelSix);
        panelSix.setLayout(panelSixLayout);
        panelSixLayout.setHorizontalGroup(
            panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p6Q2Lbl)
                    .addComponent(p6Q1Lbl)
                    .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6mainHeadingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSixLayout.createSequentialGroup()
                        .addComponent(p6maleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p6femaleBtn))
                    .addComponent(p6answer2TF)
                    .addComponent(p6Answer1TF))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelSixLayout.setVerticalGroup(
            panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSixLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p6mainHeadingLbl)
                .addGap(48, 48, 48)
                .addComponent(p6candidateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelSixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6maleBtn)
                    .addComponent(p6femaleBtn))
                .addGap(78, 78, 78)
                .addComponent(p6Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p6Answer1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(p6Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p6answer2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.add(panelSix, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUserBtnActionPerformed

    private void voterUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voterUserBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void p3Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3Answer1TFActionPerformed

    private void p4Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4Answer1TFActionPerformed

    private void p5Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5Answer1TFActionPerformed

    private void p6Answer1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6Answer1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6Answer1TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PollGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PollGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminUserBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupP3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel mainHeadingLbl;
    private javax.swing.JLabel mainHeadingLbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField p3Answer1TF;
    private javax.swing.JLabel p3Q1Lbl;
    private javax.swing.JLabel p3Q2Lbl;
    private javax.swing.JTextField p3answer2TF;
    private javax.swing.JComboBox<String> p3candidateComboBox;
    private javax.swing.JRadioButton p3femaleBtn;
    private javax.swing.JLabel p3mainHeadingLbl;
    private javax.swing.JRadioButton p3maleBtn;
    private javax.swing.JTextField p4Answer1TF;
    private javax.swing.JLabel p4Q1Lbl;
    private javax.swing.JLabel p4Q2Lbl;
    private javax.swing.JTextField p4answer2TF;
    private javax.swing.JComboBox<String> p4candidateComboBox;
    private javax.swing.JRadioButton p4femaleBtn;
    private javax.swing.JLabel p4mainHeadingLbl;
    private javax.swing.JRadioButton p4maleBtn;
    private javax.swing.JTextField p5Answer1TF;
    private javax.swing.JLabel p5Q1Lbl;
    private javax.swing.JLabel p5Q2Lbl;
    private javax.swing.JTextField p5answer2TF;
    private javax.swing.JComboBox<String> p5candidateComboBox;
    private javax.swing.JRadioButton p5femaleBtn;
    private javax.swing.JLabel p5mainHeadingLbl;
    private javax.swing.JRadioButton p5maleBtn;
    private javax.swing.JTextField p6Answer1TF;
    private javax.swing.JLabel p6Q1Lbl;
    private javax.swing.JLabel p6Q2Lbl;
    private javax.swing.JTextField p6answer2TF;
    private javax.swing.JComboBox<String> p6candidateComboBox;
    private javax.swing.JRadioButton p6femaleBtn;
    private javax.swing.JLabel p6mainHeadingLbl;
    private javax.swing.JRadioButton p6maleBtn;
    private javax.swing.JPanel panelFive;
    private javax.swing.JPanel panelFour;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel panelSix;
    private javax.swing.JPanel panelThree;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JLabel userTypeLbl;
    private javax.swing.JButton voterUserBtn;
    // End of variables declaration//GEN-END:variables

    void visible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
}
